'use client';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import { useState } from 'react';
import IconMenu from "@/../public/menu.png";
import AvatarImg from "@/../public/blankProfilePic.webp";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  const [isOpen, setIsOpen] = useState(true);

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        
        <div className="w-screen h-screen flex gap-5 bg-gray-200 box-border">

          <div className={`bg-gray-800 text-gray-100 min-w-[200px] w-1/4 h-full transition-all duration-300 flex top-0 left-0 justify-start items-center flex-col p-[30px] pt-[60px] shadow-xl overflow-x-hidden overflow-y-auto ${isOpen ? 'translate-x-0' : '-translate-x-[100%]'}`}>

            <img src={AvatarImg.src} alt="Avatar" className="w-[40px] h-[40px] mt-6 rounded-full"/>
            <h1 className="mt-4">使用者</h1>

            <div>
              
              {/* 頁面切換 */}
              
              <Link href="/home">
                <div className={`flex w-[16vw] p-3 px-4 mt-4 hover:bg-gray-700 hover:text-white rounded`}>首頁</div>
              </Link>

              <Link href="/profile">
                <div className={`flex w-[16vw] p-3 px-4 mt-2 hover:bg-gray-700 hover:text-white rounded`}>個人資料</div>
              </Link>

              <Link href="/portfolio">
                <div className={`flex w-[16vw] p-3 px-4 mt-2 hover:bg-gray-700 hover:text-white rounded`}>學習歷程</div>
              </Link>

              <Link href="/schedule">
                <div className={`flex w-[16vw] p-3 px-4 mt-2 hover:bg-gray-700 hover:text-white rounded`}>日程表</div>
              </Link>

              <Link href="/settings">
                <div className={`flex w-[16vw] p-3 px-4 mt-2 hover:bg-gray-700 hover:text-white rounded`}>設定</div>
              </Link>
              
              <Link href="/faq">
                <div className={`flex w-[16vw] p-3 px-4 mt-2 hover:bg-gray-700 hover:text-white rounded`}>常見問題</div>
              </Link>

            </div>

          </div>

          {/* Toggle Button */}
          <button onClick={() => setIsOpen(!isOpen)}
              className="p-2 fixed top-4 left-4 z-50">
            <div className="bg-gray-100 w-[40px] h-[40px] rounded-2xl relative">

              <Image src={IconMenu} alt="Menu" className="w-[24px] h-[24px] absolute top-[8px] left-[8px]" />
            </div>
          </button>

          {children}

          
        </div>
      </body>
    </html> 
  );
}
